### ISSUE TITLE
UCM

### ISSUE THREAD

**Issue by NoahSantander** [pdepjm/2023-tp0-presentacion-valendelrizzo#2]
Cual es tu película favorita del UCM? PD: No me hagas decidir entre Steve o Tony

**Comment by valendelrizzo** [comment]
Sin duda alguna, Endgame. Daría un comentario pero no quiero tirar spoilers, se que salió hace un tiempo ya, pero por las dudas no digo nada jajaja. Y la tuya?

**Comment by NoahSantander** [comment]
Capitán América 1. Una gran película bélica con uno de los mejores finales de una película del UCM

**Comment by valendelrizzo** [comment]
Coincido totalmente. También me gusta mucho Civil War, el desarrollo es muy bueno.
